FROM node:14

COPY files/aaaaaaaaaaaaaaaaaaaaaaa/aaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaa/aaaaaaaaa/aaaaaaaaaaaaaaaa/aaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaa/aaa.txt .
COPY files/aaaaaaaaaaaaaaaaaaaaaaa/aaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaa/aaaaaaaaa/aaaaaaaaaaaaaaaa/aaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaa/bbbb.txt .
COPY files/aaaaaaaaaaaaaaaaaaaaaaa/aaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaa/aaaaaaaaa/aaaaaaaaaaaaaaaa/aaaaaaaaaa/aaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaa/ccccc.txt .

# COPY files .